import { CategoriesType } from '@root/types/food';

export const foodMocks = [
  {
    id: 1,
    imageUrl: 'https://loremflickr.com/400/400?random=1',
    name: 'Омлет с зеленью',
    description: 'Нежный омлет с добавлением свежей зелени и специй.',
    price: 120,
    weight: 150,
    type: CategoriesType.Brunch,
  },
  {
    id: 2,
    imageUrl: 'https://loremflickr.com/400/400?random=2',
    name: 'Клубничный чизкейк',
    description: 'Кремовый чизкейк с ярким клубничным вкусом.',
    price: 250,
    weight: 200,
    type: CategoriesType.Dessert,
  },
  {
    id: 3,
    imageUrl: 'https://loremflickr.com/400/400?random=3',
    name: 'Пицца с сыром',
    description: 'Горячая пицца с тягучим сыром и ароматными травами.',
    price: 500,
    weight: 400,
    type: CategoriesType.Lunch,
  },
  {
    id: 4,
    imageUrl: 'https://loremflickr.com/400/400?random=4',
    name: 'Шоколадный торт',
    description: 'Насыщенный шоколадный вкус в каждом кусочке.',
    price: 350,
    weight: 300,
    type: CategoriesType.Dessert,
  },
  {
    id: 5,
    imageUrl: 'https://loremflickr.com/400/400?random=5',
    name: 'Фруктовый салат',
    description: 'Смесь свежих фруктов с легким медовым соусом.',
    price: 180,
    weight: 250,
    type: CategoriesType.Brunch,
  },
  {
    id: 6,
    imageUrl: 'https://loremflickr.com/400/400?random=6',
    name: 'Картофельный крем-суп',
    description: 'Густой и согревающий крем-суп из картофеля и сливок.',
    price: 220,
    weight: 300,
    type: CategoriesType.Lunch,
  },
  {
    id: 7,
    imageUrl: 'https://loremflickr.com/400/400?random=7',
    name: 'Блинчики с вареньем',
    description: 'Тонкие блинчики с домашним ягодным вареньем.',
    price: 150,
    weight: 200,
    type: CategoriesType.Brunch,
  },
  {
    id: 8,
    imageUrl: 'https://loremflickr.com/400/400?random=8',
    name: 'Тирамису',
    description: 'Итальянский десерт с нежным кремом и кофейным ароматом.',
    price: 300,
    weight: 150,
    type: CategoriesType.Dessert,
  },
  {
    id: 9,
    imageUrl: 'https://loremflickr.com/400/400?random=9',
    name: 'Сэндвич с курицей',
    description: 'Сытный сэндвич с куриным филе, овощами и соусом.',
    price: 200,
    weight: 250,
    type: CategoriesType.Brunch,
  },
  {
    id: 10,
    imageUrl: 'https://loremflickr.com/400/400?random=10',
    name: 'Ризотто с грибами',
    description: 'Кремовое ризотто с ароматными лесными грибами.',
    price: 450,
    weight: 350,
    type: CategoriesType.Lunch,
  },
  {
    id: 11,
    imageUrl: 'https://loremflickr.com/400/400?random=11',
    name: 'Салат Цезарь',
    description: 'Классический салат с курицей, сухариками и соусом Цезарь.',
    price: 320,
    weight: 250,
    type: CategoriesType.Lunch,
  },
  {
    id: 12,
    imageUrl: 'https://loremflickr.com/400/400?random=12',
    name: 'Ягодный смузи',
    description: 'Освежающий смузи из свежих ягод и йогурта.',
    price: 150,
    weight: 300,
    type: CategoriesType.Brunch,
  },
  {
    id: 13,
    imageUrl: 'https://loremflickr.com/400/400?random=13',
    name: 'Брауни',
    description: 'Шоколадный десерт с орехами и нежной текстурой.',
    price: 200,
    weight: 120,
    type: CategoriesType.Dessert,
  },
  {
    id: 14,
    imageUrl: 'https://loremflickr.com/400/400?random=14',
    name: 'Том Ям',
    description: 'Острый тайский суп с креветками и кокосовым молоком.',
    price: 480,
    weight: 400,
    type: CategoriesType.Lunch,
  },
  {
    id: 15,
    imageUrl: 'https://loremflickr.com/400/400?random=15',
    name: 'Вафли с мороженым',
    description: 'Хрустящие вафли с шариком сливочного мороженого.',
    price: 250,
    weight: 200,
    type: CategoriesType.Dessert,
  },
  {
    id: 16,
    imageUrl: 'https://loremflickr.com/400/400?random=16',
    name: 'Бургер с говядиной',
    description: 'Сочный бургер с говяжьей котлетой и свежими овощами.',
    price: 450,
    weight: 350,
    type: CategoriesType.Lunch,
  },
  {
    id: 17,
    imageUrl: 'https://loremflickr.com/400/400?random=17',
    name: 'Сырники',
    description: 'Традиционные сырники из творога с ванильным соусом.',
    price: 200,
    weight: 200,
    type: CategoriesType.Brunch,
  },
  {
    id: 18,
    imageUrl: 'https://loremflickr.com/400/400?random=18',
    name: 'Крем-брюле',
    description: 'Французский десерт с карамельной корочкой.',
    price: 280,
    weight: 150,
    type: CategoriesType.Dessert,
  },
  {
    id: 19,
    imageUrl: 'https://loremflickr.com/400/400?random=19',
    name: 'Шашлык из курицы',
    description: 'Сочное куриное мясо, приготовленное на углях.',
    price: 400,
    weight: 300,
    type: CategoriesType.Lunch,
  },
  {
    id: 20,
    imageUrl: 'https://loremflickr.com/400/400?random=20',
    name: 'Фруктовый тарт',
    description: 'Песочный тарт с кремом и свежими фруктами.',
    price: 350,
    weight: 180,
    type: CategoriesType.Dessert,
  },
  {
    id: 21,
    imageUrl: 'https://loremflickr.com/400/400?random=21',
    name: 'Овсянка с фруктами',
    description: 'Горячая овсяная каша с добавлением фруктов и орехов.',
    price: 150,
    weight: 300,
    type: CategoriesType.Brunch,
  },
  {
    id: 22,
    imageUrl: 'https://loremflickr.com/400/400?random=22',
    name: 'Куриный суп',
    description: 'Легкий и питательный куриный суп с лапшой.',
    price: 220,
    weight: 350,
    type: CategoriesType.Lunch,
  },
  {
    id: 23,
    imageUrl: 'https://loremflickr.com/400/400?random=23',
    name: 'Тарталетки с ягодами',
    description: 'Мини-десерты с песочной основой и ягодным наполнением.',
    price: 180,
    weight: 150,
    type: CategoriesType.Dessert,
  },
  {
    id: 24,
    imageUrl: 'https://loremflickr.com/400/400?random=24',
    name: 'Роллы Калифорния',
    description: 'Классические роллы с крабом и авокадо.',
    price: 320,
    weight: 250,
    type: CategoriesType.Lunch,
  },
  {
    id: 25,
    imageUrl: 'https://loremflickr.com/400/400?random=25',
    name: 'Греческий салат',
    description: 'Свежий салат с фетой, оливками и овощами.',
    price: 200,
    weight: 250,
    type: CategoriesType.Brunch,
  },
  {
    id: 26,
    imageUrl: 'https://loremflickr.com/400/400?random=26',
    name: 'Эклеры',
    description: 'Нежные эклеры с кремом из ванили.',
    price: 250,
    weight: 180,
    type: CategoriesType.Dessert,
  },
  {
    id: 27,
    imageUrl: 'https://loremflickr.com/400/400?random=27',
    name: 'Куриные наггетсы',
    description: 'Хрустящие куриные наггетсы с соусом барбекю.',
    price: 300,
    weight: 200,
    type: CategoriesType.Lunch,
  },
  {
    id: 28,
    imageUrl: 'https://loremflickr.com/400/400?random=28',
    name: 'Пудинг из манго',
    description: 'Десерт с насыщенным вкусом спелого манго.',
    price: 280,
    weight: 200,
    type: CategoriesType.Dessert,
  },
  {
    id: 29,
    imageUrl: 'https://loremflickr.com/400/400?random=29',
    name: 'Салат с тунцом',
    description: 'Питательный салат с тунцом, овощами и соусом.',
    price: 240,
    weight: 250,
    type: CategoriesType.Lunch,
  },
  {
    id: 30,
    imageUrl: 'https://loremflickr.com/400/400?random=30',
    name: 'Маффин с черникой',
    description: 'Мягкий маффин с начинкой из черники.',
    price: 180,
    weight: 120,
    type: CategoriesType.Dessert,
  },
  {
    id: 31,
    imageUrl: 'https://loremflickr.com/400/400?random=31',
    name: 'Паста Карбонара',
    description: 'Итальянская паста с беконом, сливками и сыром.',
    price: 350,
    weight: 300,
    type: CategoriesType.Lunch,
  },
  {
    id: 32,
    imageUrl: 'https://loremflickr.com/400/400?random=32',
    name: 'Круассан с шоколадом',
    description: 'Воздушный круассан с начинкой из растопленного шоколада.',
    price: 200,
    weight: 150,
    type: CategoriesType.Brunch,
  },
  {
    id: 33,
    imageUrl: 'https://loremflickr.com/400/400?random=33',
    name: 'Суп-пюре из тыквы',
    description: 'Кремовый суп с ярким вкусом тыквы и пряностями.',
    price: 250,
    weight: 300,
    type: CategoriesType.Lunch,
  },
  {
    id: 34,
    imageUrl: 'https://loremflickr.com/400/400?random=34',
    name: 'Шоколадное фондю',
    description: 'Растопленный шоколад с кусочками фруктов для макания.',
    price: 400,
    weight: 250,
    type: CategoriesType.Dessert,
  },
  {
    id: 35,
    imageUrl: 'https://loremflickr.com/400/400?random=35',
    name: 'Куриный салат с ананасами',
    description: 'Легкий салат с курицей, ананасами и орехами.',
    price: 300,
    weight: 250,
    type: CategoriesType.Brunch,
  },
  {
    id: 36,
    imageUrl: 'https://loremflickr.com/400/400?random=36',
    name: 'Бефстроганов',
    description: 'Кусочки говядины в сливочном соусе с луком.',
    price: 450,
    weight: 350,
    type: CategoriesType.Lunch,
  },
  {
    id: 37,
    imageUrl: 'https://loremflickr.com/400/400?random=37',
    name: 'Панкейки с сиропом',
    description: 'Нежные панкейки с кленовым сиропом и ягодами.',
    price: 220,
    weight: 200,
    type: CategoriesType.Brunch,
  },
  {
    id: 38,
    imageUrl: 'https://loremflickr.com/400/400?random=38',
    name: 'Чизкейк Нью-Йорк',
    description: 'Классический чизкейк с нежным сырным кремом.',
    price: 350,
    weight: 200,
    type: CategoriesType.Dessert,
  },
  {
    id: 39,
    imageUrl: 'https://loremflickr.com/400/400?random=39',
    name: 'Плов с бараниной',
    description: 'Рассыпчатый плов с кусочками баранины и овощами.',
    price: 480,
    weight: 400,
    type: CategoriesType.Lunch,
  },
  {
    id: 40,
    imageUrl: 'https://loremflickr.com/400/400?random=40',
    name: 'Фрукты в шоколаде',
    description: 'Ассорти из свежих фруктов, покрытых растопленным шоколадом.',
    price: 300,
    weight: 250,
    type: CategoriesType.Dessert,
  },
  {
    id: 41,
    imageUrl: 'https://loremflickr.com/400/400?random=41',
    name: 'Гречка с грибами',
    description: 'Питательное блюдо из гречки с жареными грибами.',
    price: 180,
    weight: 300,
    type: CategoriesType.Lunch,
  },
  {
    id: 42,
    imageUrl: 'https://loremflickr.com/400/400?random=42',
    name: 'Творожная запеканка',
    description: 'Сладкая запеканка из творога с изюмом.',
    price: 200,
    weight: 250,
    type: CategoriesType.Brunch,
  },
  {
    id: 43,
    imageUrl: 'https://loremflickr.com/400/400?random=43',
    name: 'Фруктовое желе',
    description: 'Освежающий десерт с кусочками фруктов.',
    price: 150,
    weight: 200,
    type: CategoriesType.Dessert,
  },
  {
    id: 44,
    imageUrl: 'https://loremflickr.com/400/400?random=44',
    name: 'Салат Оливье',
    description: 'Традиционный русский салат с овощами и мясом.',
    price: 250,
    weight: 300,
    type: CategoriesType.Lunch,
  },
  {
    id: 45,
    imageUrl: 'https://loremflickr.com/400/400?random=45',
    name: 'Шарлотка с яблоками',
    description: 'Домашняя выпечка с ароматной яблочной начинкой.',
    price: 220,
    weight: 200,
    type: CategoriesType.Dessert,
  },
  {
    id: 46,
    imageUrl: 'https://loremflickr.com/400/400?random=46',
    name: 'Гаспачо',
    description: 'Холодный испанский суп из свежих овощей.',
    price: 300,
    weight: 350,
    type: CategoriesType.Lunch,
  },
  {
    id: 47,
    imageUrl: 'https://loremflickr.com/400/400?random=47',
    name: 'Кукурузные хлопья с молоком',
    description: 'Легкий и быстрый завтрак с хрустящими хлопьями.',
    price: 120,
    weight: 200,
    type: CategoriesType.Brunch,
  },
  {
    id: 48,
    imageUrl: 'https://loremflickr.com/400/400?random=48',
    name: 'Тарталетки с кремом',
    description: 'Хрустящие тарталетки с ванильным кремом.',
    price: 250,
    weight: 180,
    type: CategoriesType.Dessert,
  },
  {
    id: 49,
    imageUrl: 'https://loremflickr.com/400/400?random=49',
    name: 'Лапша удон с овощами',
    description: 'Японское блюдо с лапшой удон, овощами и соусом.',
    price: 400,
    weight: 350,
    type: CategoriesType.Lunch,
  },
  {
    id: 50,
    imageUrl: 'https://loremflickr.com/400/400?random=50',
    name: 'Пирог с вишней',
    description: 'Сладкий пирог с вишневой начинкой и хрустящей корочкой.',
    price: 300,
    weight: 250,
    type: CategoriesType.Dessert,
  },
];
