/* eslint-disable global-require  */
import { CategoriesType } from '@root/types/food';

export const foodMocks = [
  {
    id: 1,
    imageUrl: require('./assets/omlet-s-zelenyu.jpg'),
    name: 'Омлет с зеленью',
    description: 'Нежный омлет с добавлением свежей зелени и специй.',
    price: 120,
    weight: 150,
    type: CategoriesType.Brunch,
  },
  {
    id: 2,
    imageUrl: require('./assets/strawberry-cheesecake.webp'),
    name: 'Клубничный чизкейк',
    description: 'Кремовый чизкейк с ярким клубничным вкусом.',
    price: 250,
    weight: 200,
    type: CategoriesType.Dessert,
  },
  {
    id: 3,
    imageUrl: require('./assets/picca-s-syrom.jpg'),
    name: 'Пицца с сыром',
    description: 'Горячая пицца с тягучим сыром и ароматными травами.',
    price: 500,
    weight: 400,
    type: CategoriesType.Lunch,
  },
  {
    id: 4,
    imageUrl: require('./assets/chokolate-beeskweet.jpg'),
    name: 'Шоколадный торт',
    description: 'Насыщенный шоколадный вкус в каждом кусочке.',
    price: 350,
    weight: 300,
    type: CategoriesType.Dessert,
  },
  {
    id: 5,
    imageUrl: require('./assets/fruit-salat.jpg'),
    name: 'Фруктовый салат',
    description: 'Смесь свежих фруктов с легким медовым соусом.',
    price: 180,
    weight: 250,
    type: CategoriesType.Brunch,
  },
  {
    id: 6,
    imageUrl: require('./assets/potato-soup.jpg'),
    name: 'Картофельный крем-суп',
    description: 'Густой и согревающий крем-суп из картофеля и сливок.',
    price: 220,
    weight: 300,
    type: CategoriesType.Lunch,
  },
  {
    id: 7,
    imageUrl: require('./assets/strawbeary-blin.jpeg'),
    name: 'Блинчики с вареньем',
    description: 'Тонкие блинчики с домашним ягодным вареньем.',
    price: 150,
    weight: 200,
    type: CategoriesType.Brunch,
  },
  {
    id: 8,
    imageUrl: require('./assets/tiramisu.jpg'),
    name: 'Тирамису',
    description: 'Итальянский десерт с нежным кремом и кофейным ароматом.',
    price: 300,
    weight: 150,
    type: CategoriesType.Dessert,
  },
  {
    id: 9,
    imageUrl: require('./assets/sandwich.jpg'),
    name: 'Сэндвич с курицей',
    description: 'Сытный сэндвич с куриным филе, овощами и соусом.',
    price: 200,
    weight: 250,
    type: CategoriesType.Brunch,
  },
  {
    id: 10,
    imageUrl: require('./assets/risoto.jpg'),
    name: 'Ризотто с грибами',
    description: 'Кремовое ризотто с ароматными лесными грибами.',
    price: 450,
    weight: 350,
    type: CategoriesType.Lunch,
  },
  {
    id: 11,
    imageUrl: require('./assets/cezar.jpg'),
    name: 'Салат Цезарь',
    description: 'Классический салат с курицей, сухариками и соусом Цезарь.',
    price: 320,
    weight: 250,
    type: CategoriesType.Lunch,
  },
  {
    id: 12,
    imageUrl: require('./assets/smuzi.webp'),
    name: 'Ягодный смузи',
    description: 'Освежающий смузи из свежих ягод и йогурта.',
    price: 150,
    weight: 300,
    type: CategoriesType.Brunch,
  },
  {
    id: 13,
    imageUrl: require('./assets/brauny.jpg'),
    name: 'Брауни',
    description: 'Шоколадный десерт с орехами и нежной текстурой.',
    price: 200,
    weight: 120,
    type: CategoriesType.Dessert,
  },
  {
    id: 14,
    imageUrl: require('./assets/tom-yan.jpg'),
    name: 'Том Ям',
    description: 'Острый тайский суп с креветками и кокосовым молоком.',
    price: 480,
    weight: 400,
    type: CategoriesType.Lunch,
  },
  {
    id: 15,
    imageUrl: require('./assets/vafl-with-icecream.jpg'),
    name: 'Вафли с мороженым',
    description: 'Хрустящие вафли с шариком сливочного мороженого.',
    price: 250,
    weight: 200,
    type: CategoriesType.Dessert,
  },
  {
    id: 16,
    imageUrl: require('./assets/burget-with-beaf.jpg'),
    name: 'Бургер с говядиной',
    description: 'Сочный бургер с говяжьей котлетой и свежими овощами.',
    price: 450,
    weight: 350,
    type: CategoriesType.Lunch,
  },
  {
    id: 17,
    imageUrl: require('./assets/sirniki.jpg'),
    name: 'Сырники',
    description: 'Традиционные сырники из творога с ванильным соусом.',
    price: 200,
    weight: 200,
    type: CategoriesType.Brunch,
  },
  {
    id: 18,
    imageUrl: require('./assets/krem-brule.jpg'),
    name: 'Крем-брюле',
    description: 'Французский десерт с карамельной корочкой.',
    price: 280,
    weight: 150,
    type: CategoriesType.Dessert,
  },
  {
    id: 19,
    imageUrl: require('./assets/shaslik.jpg'),
    name: 'Шашлык из курицы',
    description: 'Сочное куриное мясо, приготовленное на углях.',
    price: 400,
    weight: 300,
    type: CategoriesType.Lunch,
  },
  {
    id: 20,
    imageUrl: require('./assets/fruit-tart.jpg'),
    name: 'Фруктовый тарт',
    description: 'Песочный тарт с кремом и свежими фруктами.',
    price: 350,
    weight: 180,
    type: CategoriesType.Dessert,
  },
  {
    id: 21,
    imageUrl: require('./assets/ovsyna-kasha.webp'),
    name: 'Овсянка с фруктами',
    description: 'Горячая овсяная каша с добавлением фруктов и орехов.',
    price: 150,
    weight: 300,
    type: CategoriesType.Brunch,
  },
  {
    id: 22,
    imageUrl: require('./assets/soup-with-chiken.jpg'),
    name: 'Куриный суп',
    description: 'Легкий и питательный куриный суп с лапшой.',
    price: 220,
    weight: 350,
    type: CategoriesType.Lunch,
  },
  {
    id: 23,
    imageUrl: require('./assets/tartaletki.jpg'),
    name: 'Тарталетки с ягодами',
    description: 'Мини-десерты с песочной основой и ягодным наполнением.',
    price: 180,
    weight: 150,
    type: CategoriesType.Dessert,
  },
  {
    id: 24,
    imageUrl: require('./assets/rolli-kaliforniya.jpg'),
    name: 'Роллы Калифорния',
    description: 'Классические роллы с крабом и авокадо.',
    price: 320,
    weight: 250,
    type: CategoriesType.Lunch,
  },
  {
    id: 25,
    imageUrl: require('./assets/greek-salat.jpg'),
    name: 'Греческий салат',
    description: 'Свежий салат с фетой, оливками и овощами.',
    price: 200,
    weight: 250,
    type: CategoriesType.Brunch,
  },
  {
    id: 26,
    imageUrl: require('./assets/ecler.jpg'),
    name: 'Эклеры',
    description: 'Нежные эклеры с кремом из ванили.',
    price: 250,
    weight: 180,
    type: CategoriesType.Dessert,
  },
  {
    id: 27,
    imageUrl: require('./assets/nagets.jpg'),
    name: 'Куриные наггетсы',
    description: 'Хрустящие куриные наггетсы с соусом барбекю.',
    price: 300,
    weight: 200,
    type: CategoriesType.Lunch,
  },
  {
    id: 28,
    imageUrl: require('./assets/puding-from-mango.jpg'),
    name: 'Пудинг из манго',
    description: 'Десерт с насыщенным вкусом спелого манго.',
    price: 280,
    weight: 200,
    type: CategoriesType.Dessert,
  },
  {
    id: 29,
    imageUrl: require('./assets/salat-s-tuntsom.webp'),
    name: 'Салат с тунцом',
    description: 'Питательный салат с тунцом, овощами и соусом.',
    price: 240,
    weight: 250,
    type: CategoriesType.Lunch,
  },
  {
    id: 30,
    imageUrl: require('./assets/maffin-with-berry.jpg'),
    name: 'Маффин с черникой',
    description: 'Мягкий маффин с начинкой из черники.',
    price: 180,
    weight: 120,
    type: CategoriesType.Dessert,
  },
  {
    id: 31,
    imageUrl: require('./assets/spagetti-karbonara-s-bekonom.jpg'),
    name: 'Паста Карбонара',
    description: 'Итальянская паста с беконом, сливками и сыром.',
    price: 350,
    weight: 300,
    type: CategoriesType.Lunch,
  },
  {
    id: 32,
    imageUrl: require('./assets/kruassany.jpg'),
    name: 'Круассан с шоколадом',
    description: 'Воздушный круассан с начинкой из растопленного шоколада.',
    price: 200,
    weight: 150,
    type: CategoriesType.Brunch,
  },
  {
    id: 33,
    imageUrl: require('./assets/soup-pire.webp'),
    name: 'Суп-пюре из тыквы',
    description: 'Кремовый суп с ярким вкусом тыквы и пряностями.',
    price: 250,
    weight: 300,
    type: CategoriesType.Lunch,
  },
  {
    id: 34,
    imageUrl: require('./assets/chokolate-fondy.webp'),
    name: 'Шоколадное фондю',
    description: 'Растопленный шоколад с кусочками фруктов для макания.',
    price: 400,
    weight: 250,
    type: CategoriesType.Dessert,
  },
  {
    id: 35,
    imageUrl: require('./assets/chiken-salat.jpg'),
    name: 'Куриный салат с ананасами',
    description: 'Легкий салат с курицей, ананасами и орехами.',
    price: 300,
    weight: 250,
    type: CategoriesType.Brunch,
  },
];
